### PR TITLE
Update cmdview.py

### PR DESCRIPTION
**Pull request by sajjadhossanshimanto**
I've already opened issue complaining about Cli View.So when I was looking into code to manually start the download I saw this print issue.
IMG_20211203_205353

So I really don't want to leave this opportunity to register my name on contributors list.

### CODE REVIEW

**Comment by firedm** [comment]
@sajjadhossanshimanto 
thanks for the effort
unfortunately the modification you suggested will cause the progress line to be overwritten, i.e. you will never see progress line at 100%

also to get reliable results, you should try it in real terminal window instead of vscode

I'm sorry to decline this PR, but I'm sure you can contribute something else and get into contributors list soon.

**Comment by sajjadhossanshimanto** [comment]
This is how the terminal view looks like outside of vscode.
IMG_20211204_131144


And for showing 99% and 100% progress [report_d](https://github.com/firedm/FireDM/blob/be551dc59fa1ffa8b29bc48a300e72cafdaba4b3/firedm/controller.py#L975) is already placed at the end of _download. Raw print is not related to this

IMG_20211204_133725


I hope you would reconsider the changes

**Comment by firedm** [comment]
No problem, will accept changes

**Comment by firedm** [comment]
Thanks for your work

**Comment by sajjadhossanshimanto** [comment]
@firedm 
I'm great Full for being a part of this wonderful project.
If you don't mind I can take the responsibility to repair the cli view #386

**Comment by firedm** [comment]
@sajjadhossanshimanto 
Thanks for your participation and you are welcome in FireDM team

> I can take the responsibility to repair the cli view #386

no need, i'm almost done with this fix, 

if you wish to help, then we need to work on cmdview progressbar to make it like "apt install" progressbar in ubuntu "i.e. progressbar stay at the bottom all the time while other print statements flow naturally", but without using 3rd party libraries, and works on linux and windows, 
let me know if this is ok with

**Comment by firedm** [comment]
here it is a beautiful topic about apt progressbar that we need to implement
https://mdk.fr/blog/how-apt-does-its-fancy-progress-bar.html

**Comment by sajjadhossanshimanto** [comment]
Thanks for this opportunity.
I think I'm ok with that. I will try my best. After You fix #386 I would start my job.
Or let my know I need to start now.

**Comment by firedm** [comment]
@sajjadhossanshimanto 
No problem you can start now, #386 fix will not touch cmdview.py file
if you need any help let me know, good luck

**Pull request merged**
