### PR TITLE
Adding function to return duration of video or audio fle

### PR DESCRIPTION
**Pull request by fidele000**
i created a function from **utils.py** file to return a tuple duration of a video or audio from local or URL, i wonder adding it to a GUI class to generate file properties

### CODE REVIEW

**Comment by firedm** [comment]
@fidele000 
thanks for the effort,
the video duration is needed before downloading the file, not after, so we have no file on disk to check its duration

these a guides on how to do it:
- video duration will be available when fetching video metadata.
- video metadata will be passed as dictionary to "[Video class](https://github.com/firedm/FireDM/blob/cfff978010c6d405cba41cd28b8a8d79ea44df4f/firedm/video.py#L92)"  as "vid_info)" parameter.
- there is 2 keys in "video_info",  one is 'duration' which is video duration in seconds, and  'duration_string' which is representation of time  e.g  '43:31' for 43 minutes and 31 seconds.
- will add 2 properties to "Video class" with same names, e.g. `self.duration = self.video_info.get('duration', None)` and same for self.duration_string.
- to make this info available for gui we need to add `'duration', 'duration_string'` to  "[watch_list](https://github.com/firedm/FireDM/blob/cfff978010c6d405cba41cd28b8a8d79ea44df4f/firedm/model.py#L29)"  in Observable class
- after that these info will reach gui, we need to show duration in "[FileProperties](https://github.com/firedm/FireDM/blob/cfff978010c6d405cba41cd28b8a8d79ea44df4f/firedm/tkview.py#L1117)" class, where "duration" should be displayed next to "Resumable" status in "[misc](https://github.com/firedm/FireDM/blob/cfff978010c6d405cba41cd28b8a8d79ea44df4f/firedm/tkview.py#L1226)" frame

**Comment by fidele000** [comment]
thank you, i did that but i gon't understand the logic of GUI to display the value to the label
@firedm

**Comment by firedm** [comment]
@fidele000 

good work,
will merge your pull request and do slight modifications later on to display value in GUI

**Comment by fidele000** [comment]
@firedm sure Kindly share what you changed for better understanding of the GUI.

Thanks

**Comment by firedm** [comment]
@fidele000 
added changes in commit https://github.com/firedm/FireDM/commit/3d16e77f22969fa04304daa9c9811a053c427aa9

**Pull request merged**
