### PR TITLE
Fluid progress bar

### PR DESCRIPTION
**Pull request by sajjadhossanshimanto**
Special thanks to this [article]( https://mdk.fr/blog/how-apt-does-its-fancy-progress-bar.html ) and @firedm 

Features:
1. Full time Progress bar at the buttom
2. Interactive. Adjust terminal size changes
3. Cross platform support. (Tested on Linux only)
4. without using 3rd party libraries

Please check if it works on all the other platforms.
And let me know my code need any improvement.

### CODE REVIEW

**Comment by firedm** [comment]
@sajjadhossanshimanto 
great effort, 
will test it and let you know the result

**Comment by firedm** [comment]
tested on linux and it works well

but unfortunately it didn't work well on windows, and it print junk letters
image

**Comment by firedm** [comment]
i suggest to limit this feature on Linux machines only until we fix windows cmdline, what do you think

**Comment by sajjadhossanshimanto** [comment]
This is really a bad think about windows cmd. It doesn't respond correctly with essence sequence. I've also faced this problem on my early projects. I think it need more web search.
For now I'm just limiting it for Linux. I'm hoping to fix it for windows soon

**Comment by sajjadhossanshimanto** [comment]
I believe this [forum](https://www.dostips.com/forum/viewtopic.php?t=9144) has the solution which needs tobe implemented with ctypes. But unfortunately I'm far away from windows now.

**Comment by firedm** [comment]
> I believe this [forum](https://www.dostips.com/forum/viewtopic.php?t=9144) has the solution which needs tobe implemented with ctypes. But unfortunately I'm far away from windows now.

no problem, i will chase this topic when i get a time window

**Pull request merged**
